version: 1
update_configs:
  - directory: /chat-bot/lex-model/
    package_manager: javascript
    update_schedule: monthly
    version_requirement_updates: increase_versions
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"

  - directory: /chat-bot/bot/
    package_manager: javascript
    update_schedule: monthly
    version_requirement_updates: increase_versions
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"

  - directory: /trivia-backend/app/
    package_manager: javascript
    update_schedule: monthly
    version_requirement_updates: increase_versions
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"

  - directory: /trivia-backend/base/
    package_manager: docker
    update_schedule: monthly
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"

  - directory: /trivia-backend/infra/cdk/
    package_manager: javascript
    update_schedule: monthly
    version_requirement_updates: increase_versions
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"

  - directory: /trivia-backend/infra/codedeploy-blue-green/
    package_manager: javascript
    update_schedule: monthly
    version_requirement_updates: increase_versions
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"

  - directory: /trivia-backend/infra/codedeploy-blue-green/hooks/
    package_manager: javascript
    update_schedule: monthly
    version_requirement_updates: increase_versions
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"

  - directory: /static-site/cdk/
    package_manager: javascript
    update_schedule: monthly
    version_requirement_updates: increase_versions
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"

  - directory: /static-site/app/
    package_manager: javascript
    update_schedule: monthly
    version_requirement_updates: increase_versions
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"

  - directory: /pipelines/
    package_manager: javascript
    update_schedule: monthly
    version_requirement_updates: increase_versions
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"

  - directory: /canaries/
    package_manager: javascript
    update_schedule: monthly
    version_requirement_updates: increase_versions
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
